# Generated by Django 3.0.11 on 2021-03-02 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0174_merge_20201222_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subevent',
            name='last_modified',
        ),
    ]
