# Generated by Django 3.0.11 on 2021-03-02 08:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0175_remove_subevent_last_modified'),
        ('sendmail', '0007_auto_20210202_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='subevent',
        ),
        migrations.AddField(
            model_name='scheduledmail',
            name='computed_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 8, 45, 21, 804501)),
        ),
        migrations.AddField(
            model_name='scheduledmail',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pretixbase.Event'),
        ),
        migrations.AddField(
            model_name='scheduledmail',
            name='last_computed',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 8, 45, 21, 804483)),
        ),
        migrations.AlterField(
            model_name='rule',
            name='send_to',
            field=models.CharField(default='customers', max_length=10),
        ),
    ]
