# Generated by Django 3.0.11 on 2021-03-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0008_auto_20210302_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledmail',
            name='computed_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='scheduledmail',
            name='last_computed',
            field=models.DateTimeField(),
        ),
    ]
