# Generated by Django 3.0.11 on 2021-03-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0009_auto_20210302_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledmail',
            name='computed_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='scheduledmail',
            name='last_computed',
            field=models.DateTimeField(null=True),
        ),
    ]
